language: R
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_d7a23806da06_key -iv $encrypted_d7a23806da06_iv
    -in deploy_key.enc -out deploy_key -d
env:
  global:
  - ENCRYPTION_LABEL: d7a23806da06
  - COMMIT_AUTHOR_EMAIL: josh.london@noaa.gov
r_binary_packages:
  - sp
  - rgdal
script: bash ./deploy.sh
